-- MySQL Script generated by MySQL Workbench
-- 04/21/15 15:48:29
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema bd_vect
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema bd_vect
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bd_vect` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `bd_vect` ;

-- -----------------------------------------------------
-- Table `bd_vect`.`Vocabulario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_vect`.`Vocabulario` (
  `id_palabra` INT NOT NULL AUTO_INCREMENT,
  `palabra` VARCHAR(100) NOT NULL,
  `frec_max` INT NULL,
  `cant_doc` INT NULL,
  PRIMARY KEY (`id_palabra`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_vect`.`Documentos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_vect`.`Documentos` (
  `id_doc` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NULL,
  PRIMARY KEY (`id_doc`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_vect`.`Posteo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_vect`.`Posteo` (
  `id_palabra` INT NOT NULL,
  `id_doc` INT NOT NULL,
  `frecuencia` INT NULL,
  PRIMARY KEY (`id_palabra`, `id_doc`),
  INDEX `fk_posteo_doc_idx` (`id_doc` ASC),
  CONSTRAINT `fk_posteo_voc`
    FOREIGN KEY (`id_palabra`)
    REFERENCES `bd_vect`.`Vocabulario` (`id_palabra`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_posteo_doc`
    FOREIGN KEY (`id_doc`)
    REFERENCES `bd_vect`.`Documentos` (`id_doc`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
